bf16: true
cutoff_len: 2048
dataset: training_data_livebench_code
dataset_dir: /home/mzli/day-3/training_data
ddp_timeout: 180000000
do_train: true
enable_thinking: true
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 2
include_num_input_tokens_seen: true
learning_rate: 5.0e-05
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 256
model_name_or_path: /home/share/models/Qwen2.5-3B
num_train_epochs: 5.0
optim: adamw_torch
output_dir: saves/Qwen2.5-3B/lora/train_2025-07-18-00-57-38
packing: false
per_device_train_batch_size: 8
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: sft
template: default
trust_remote_code: true
warmup_steps: 0
